name: Release

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          # - target: x86_64-pc-windows-gnu
          #   os: ubuntu-latest
          #   extension: .exe
          # - target: x86_64-apple-darwin
          #   os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup default stable
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: cargo build --release --target=${{ matrix.target }}
      - run: find target
      - if: github.ref_type == 'tag'
        run: gh release upload "$GITHUB_REF_NAME" 'target/${{ matrix.target }}/release/split-test'
